//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myPartyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partyTable
    {
        public int Id { get; set; }
        public string partyTheme { get; set; }
        public string partyDecorationName { get; set; }
        public string partyDecorationImage { get; set; }
        public string partyDecorationDescription { get; set; }
        public string partyDecorationPrice { get; set; }
    }
}
